#!/usr/bin/env bash

dir=~/kata-word-search

# This is for Knoppix 7.7.1 DVD
if true; then
    sudo pip install virtualenv

    cd "$dir"
    virtualenv env -p `which python3`
    source env/bin/activate
    pip freeze | tee requirements.original.knoppix
    pip install pytest
    pip install pytest-xdist
    pip freeze | tee requirements.txt.knoppix
fi

# for Ubuntu (where I did development)
if false; then
    sudo apt-get install python3.5-venv

    mkdir -p "$dir"
    cd "$dir"
    python3 -m venv env
    source env/bin/activate
    pip freeze | tee requirements.original.ubuntu
    pip install pytest
    pip install pytest-xdist
    pip freeze | tee requirements.txt.ubuntu
fi
